### ISSUE TITLE
!blocklimit mylimit formatting

### ISSUE THREAD

**Issue by Javi-SE** [N1Ran/BlockLimiter#1]
!blocklimit mylimit list is difficult to read, difficult to quickly find what you're looking for. Some line spacing between block types / limit types (grid, player) would make it much easier to read.

**Comment by scytero** [comment]
/upvote

I suggest ..
* removing entries of 0-value, e.g. MyGrid 0/n, 
* removing entries containing unselected (tehrefore false) selections, but instead 
* adding empty lines. also some underlining ("__" or "--") between sections (player/faction/grid) might help a lot
