### ISSUE TITLE
Block limits sticking after blocks are ground down

### ISSUE THREAD

**Issue by Bobothemonk** [N1Ran/BlockLimiter#10]
I have a player that placed his build and repair (server limit is 1 per player) and used it on his grid in space. He then ground it down to use on his planet base. He was able to build it on his planet base, at this point he only had 1 build and repair however !blocklimit violations showed that he had 2/1 and afew minutes later it deleted the build and repair he had on planet. He rebuilt it and then violations showed 3/1 and it again deleted the build and repair after afew minutes. This went on for sometime before eventually it showed the proper limit.

This is also being reported for other blocks as well, and also for players working on projections.

They are able to project in over the limit, there blocks do get deleted after afew minutes but after afew more minutes the rest of there blocks get deleted. Example, If you have 4 refinerys (limit 4)and you project in 4 more, it deletes the 4 you projected in, but still thinks your over limit and afew minutes later deleted the 4 you legit have.

Another note, projections are still projecting over limit in most cases.

**Comment by N1Ran** [comment]
What is he grinding it down with?  I have a feeling the build/repair doesn't trigger block removal in use.

**Comment by woikerl** [comment]
For me the first part reads like the issue from #7

**Comment by N1Ran** [comment]
fixed in 1.6.802
