### ISSUE TITLE
Possible bug with Blocklimitter blockcount with projectors.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#103]
there is possible bug with Blocklimitter blockcount with projectors.
need to investigate but for now i know this.
Player was building ship from projection, had no limits for weapons.

so some weapons where built, limits are set per player and per grid.
he turned off projector, but didnt clear the projection.
after some time, he got alert that he has overlimit and blocks where deleted.

2022/04/26 17:14:35.838 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/NovaCannon from projector 6
2022/04/26 17:14:35.840 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/NovaCannon from projector 6
2022/04/26 17:14:35.840 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/NovaCannon from projector 6
2022/04/26 17:14:35.840 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/NovaCannon from projector 6
2022/04/26 17:14:35.840 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/AegisLargeBeamBase_Large from projector 6
2022/04/26 17:14:35.998 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/AegisLargeBeamBase_Large from projector 6
2022/04/26 17:14:35.998 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/AegisLargeBeamBase_Large from projector 6
2022/04/26 17:14:35.998 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/AegisLargeBeamBase_Large from projector 6
2022/04/26 17:14:35.998 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/AegisLargeBeamBase_Large from projector 6
2022/04/26 17:14:35.998 [INFO]   Removed MyObjectBuilder_LargeMissileTurret/AegisLargeBeamBase_Large from projector 6
2022/04/26 17:14:36.166 [INFO]   Removed MyObjectBuilder_ShipGrinder/LargeShipLaserGrinderx8 from projector 6

**Comment by N1Ran** [comment]
Is this bug still relevant?

**Comment by dorimanx** [comment]
No, seems issue is now fixed. closing this bug.
