### ISSUE TITLE
Shut off UnOwned Blocks not working

### ISSUE THREAD

**Issue by Asy93** [N1Ran/BlockLimiter#105]
If you create a situation where the "Enable Ownership Transfer Blocking" sets a limited block to "Nobody" ownership, Blocklimiter does not disable the newly created unowned block. 

On our server, a welder was set to unowned, which then created an unowned survival kit and led to unwarranted PvP.

**Comment by N1Ran** [comment]
Feature does not turn off power blocks nor spawn blocks.  This was written this way intensionally

**Comment by N1Ran** [comment]
Unowned medrooms will now be shutoff if feature is enable
