### ISSUE TITLE
LimitFilterType section of config file

### ISSUE THREAD

**Issue by Gaminguru** [N1Ran/BlockLimiter#106]
Hey N1Ran! 
Loving this plugin! Great work!
I was wondering if you could explain a bit what the setting line in BlockLimiter.cfg below means and how it works. I was able to figure the rest out and it changed my server for the better! (I had to edit the <> out to be able to post it LOL)
RestrictProjection-true-/RestrictProjection >>>> IS THE PROJECTED BLOCK RESTRICTED FROM BEING PROJECTED?
      LimitFilterType-None-/LimitFilterType >>>>POSSIBLE OPTIONS None, PlayerPlayTime, GridBlockCount, FactionMemberCount, GridMass.
      LimitFilterOperator-LessThan-/LimitFilterOperator > >>>>> CONFIG PAGE LISTS <Compare>value</Comprare> 
      FilterValue-10-/FilterValue > >>>>> Numerical value for filter type? So eg.(10 Hours/GridBlockCount/FactionMemberCount/Mass)?
    </LimitItem>
    I am not sure how factioncount would play into settings and <,>,= also tie in with these "filters"
    any clarification would be greatly appreciated.
    Have a GREAT one!

I am just having a hard time understanding this one section of the settings. 
    ---Sgt_Gumb0

**Comment by Gaminguru** [comment]
My intended action is to try to limit certain blocks by player (non-factioned), and Faction (based on faction size). I am wanting to increase the allowed block count as the faction grows larger. So eg.(1 person faction=4 assemblers>>>4 person faction=8 assemblers>>>10 person faction = 12 assemblers). Am I looking in the wrong place?

**Comment by N1Ran** [comment]
Restrict Projection is as mentioned.  It enforces block limits on projections and it does a total count of the grid the projector is attached to and and remove any blocks with possibility of violating limits from the projections.  As for the limitype fileter, you are correct, the LimitFilterOperator works in tangent with that feature.   Also, Playertime is only calculated in days.

**Comment by Gaminguru** [comment]
Roger that! I appreciate your response. I will give it a try.
