### ISSUE TITLE
Certain block's not limiting even tho it has the right subtypeid

### ISSUE THREAD

**Issue by Rainman410** [N1Ran/BlockLimiter#14]
yes im trying to limit certain modded blocks but they dont seem to limit even after i do update command ingame.here is the mod pack im trying to limit the drills https://steamcommunity.com/sharedfiles/filedetails/?id=776706275                               

here is what i did to try to limit them

 <LimitItem>
      <Name>Small_Drill_Tier1</Name>
      <BlockList>
        <string>Small_Drill_Tier1</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>16</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Small_Drill_Tier2</Name>
      <BlockList>
        <string>Small_Drill_Tier2</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>12</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Small_Drill_Tier3</Name>
      <BlockList>
        <string>Small_Drill_Tier3</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Small_Drill_Tier4</Name>
      <BlockList>
        <string>Small_Drill_Tier4</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>4</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Large_Drill_Tier1</Name>
      <BlockList>
        <string>Large_Drill_Tier1</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>25</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Large_Drill_Tier2</Name>
      <BlockList>
        <string>Large_Drill_Tier2</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>15</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Large_Drill_Tier3</Name>
      <BlockList>
        <string>Large_Drill_Tier3</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Large_Drill_Tier4</Name>
      <BlockList>
        <string>Large_Drill_Tier4</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <BlockOwnerState>BuiltbyId</BlockOwnerState>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
 but does not seem to work.

**Comment by N1Ran** [comment]
This issue should be fixed.  Reopen if otherwise
