### ISSUE TITLE
Misc LimitItems "Limit Faction" option Punishment not functioning

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/BlockLimiter#15]
I created Misc LimitItems rule to limit a block to a qty by faction and found an issue specific to the Limit Faction setting.

-The block placement limit works as expected (cannot place more by hand).
-The Annoy Message appears after the limit is violated (admin pasted more, or transferred ownership)
-The Annoy Message did not continue after Torch restart
-Punishment never occurs (with any PunishmentType) for this rule (interval set to 10s)
-!blocklimit mylimit DOESN'T show a violation for that rule
-!blocklimit violations DOES show a violation for the rule
-The annoy and punishment functions begin working when the rule is switched to either Limit Grids or Limit Players

![image](https://user-images.githubusercontent.com/62247634/78264678-78174800-74d1-11ea-86c0-4008b7e58df5.png)

**Comment by N1Ran** [comment]
run `!blocklimit update` and report back

**Comment by Blaylock1988** [comment]
I gave that a shot, it didn't seem to have any affect on the issue.

**Comment by N1Ran** [comment]
ok, will take a look at it

**Comment by N1Ran** [comment]
Problem found.  Update will be pushed for this once I finish sorting through the code

**Comment by N1Ran** [comment]
updated
