### ISSUE TITLE
Players reporting overlimit on blocks that not even added to limit

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#17]
Hi,
Players reporting that they cant place blocks that i didnt added to limit, they see block limit notification.
Other players say they placed block, then removed and cant place again as they have overlimit, when checking limit, it's say 3/6 but not allowing to place blocks.

Sadly we have to remove plugin from servers, as players are confused and cant play.
Please check.

Thank you.

**Comment by N1Ran** [comment]
Could be a faction limit.  Post your config and name of the limit being reported for overlimit

**Comment by dorimanx** [comment]
here is our config:
https://pastebin.com/VqthhsV4
90+ limits.
all set or player, or grid, no faction limits.
Player got blocked on fuelmixer block, that not even here, that is strange.

**Comment by N1Ran** [comment]
What mod is fuelmixer block from? I need to cross check its typeid with your current config

**Comment by dorimanx** [comment]
here is the block definition..
    <Definition xsi:type="MyObjectBuilder_AssemblerDefinition">
      <Id>
        <TypeId>Assembler</TypeId>
        <SubtypeId>Core_Fuel_Mixer</SubtypeId>
      </Id>
      <DisplayName>Reactor Fuel Mixer</DisplayName>
      <Description>Here you can mix fuel for Ark and Hyperion Reactors</Description>
       <Icon>Textures\Icons\ic.dds</Icon>
      <CubeSize>Large</CubeSize>
      <BlockTopology>TriangleMesh</BlockTopology>
      <Size x="3" y="3" z="2" />
      <ModelOffset x="0" y="0" z="0" />
      <Model>Models\Industrial_Centrifuge_Large.mwm</Model>
      <Components>
	<Component Subtype="ReinforcedPlate" Count="600" >
                    <DeconstructId>
                        <TypeId>Ore</TypeId>
                        <SubtypeId>Scrap</SubtypeId>
                    </DeconstructId>
        </Component>
        <Component Subtype="Construction" Count="300" />
	<Component Subtype="MetalGrid" Count="300" />
	<Component Subtype="Superconductor" Count="200" />
        <Component Subtype="ArcReactorcomponent" Count="200" />
	<Component Subtype="Computer" Count="500" />
        <Component Subtype="LargeTube" Count="50" />
	<Component Subtype="KC_Component" Count="100" />
        <Component Subtype="Motor" Count="100" />
	<Component Subtype="DenseSteelPlate" Count="200" />
      </Components>
      <CriticalComponent Subtype="KC_Component" Index="0" />
      <MountPoints>
        <MountPoint Side="Back" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Front" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Bottom" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Top" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Left" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Right" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
      </MountPoints>
      <MirroringZ>Y</MirroringZ>
      <MirroringY>Z</MirroringY>
      <BuildProgressModels>
		<Model BuildPercentUpperBound="0.5" File="Models\Industrial_Centrifuge_Large_Constr2.mwm" />
		<Model BuildPercentUpperBound="1.0" File="Models\Industrial_Centrifuge_Large_Constr1.mwm" />
      </BuildProgressModels>
      <MountPoints>
	<MountPoint Side="Front" StartX="0.14" StartY="0.05" EndX="1.01" EndY="2.95" />
	<MountPoint Side="Back" StartX="2.00" StartY="0.01" EndX="2.96" EndY="2.99" />
	<MountPoint Side="Right" StartX="0.02" StartY="0.01" EndX="1.98" EndY="2.99" />
	<MountPoint Side="Bottom" StartX="0.09" StartY="0.13" EndX="2.95" EndY="1.87" />
	<MountPoint Side="Top" StartX="0.10" StartY="0.04" EndX="2.91" EndY="1.96" />
      </MountPoints>
      <BlockPairName>Hyperion_Fuel_Mixer</BlockPairName>
      <EdgeType>Light</EdgeType>
      <BuildTimeSeconds>100</BuildTimeSeconds>
      <DisassembleRatio>2.5</DisassembleRatio>
      <ResourceSinkGroup>Factory</ResourceSinkGroup>
      <InventoryMaxVolume>4</InventoryMaxVolume>
      <InventorySize>
        <X>2</X>
        <Y>2</Y>
        <Z>2</Z>
      </InventorySize>
      <StandbyPowerConsumption>0.001</StandbyPowerConsumption>
      <OperationalPowerConsumption>80</OperationalPowerConsumption>
      <BlueprintClasses>
	<Class>CoreReactor_Fuel</Class>
      </BlueprintClasses>
      <DamageEffectName>Damage_HeavyMech_Damaged</DamageEffectName>
      <DamagedSound>ParticleHeavyMech</DamagedSound>
      <PrimarySound>BlockAssembler</PrimarySound>
      <ActionSound>BlockAssemblerProcess</ActionSound>
      <DestroyEffect>Explosion_Missile</DestroyEffect>
      <DestroySound>WepSmallMissileExpl</DestroySound>
      <PCU>300</PCU>
    </Definition>

**Comment by dorimanx** [comment]
`    <Definition xsi:type="MyObjectBuilder_AssemblerDefinition">
      <Id>
        <TypeId>Assembler</TypeId>
        <SubtypeId>Core_Fuel_Mixer</SubtypeId>
      </Id>
      <DisplayName>Reactor Fuel Mixer</DisplayName>
      <Description>Here you can mix fuel for Ark and Hyperion Reactors</Description>
       <Icon>Textures\Icons\ic.dds</Icon>
      <CubeSize>Large</CubeSize>
      <BlockTopology>TriangleMesh</BlockTopology>
      <Size x="3" y="3" z="2" />
      <ModelOffset x="0" y="0" z="0" />
      <Model>Models\Industrial_Centrifuge_Large.mwm</Model>
      <Components>
	<Component Subtype="ReinforcedPlate" Count="600" >
                    <DeconstructId>
                        <TypeId>Ore</TypeId>
                        <SubtypeId>Scrap</SubtypeId>
                    </DeconstructId>
        </Component>
        <Component Subtype="Construction" Count="300" />
	<Component Subtype="MetalGrid" Count="300" />
	<Component Subtype="Superconductor" Count="200" />
        <Component Subtype="ArcReactorcomponent" Count="200" />
	<Component Subtype="Computer" Count="500" />
        <Component Subtype="LargeTube" Count="50" />
	<Component Subtype="KC_Component" Count="100" />
        <Component Subtype="Motor" Count="100" />
	<Component Subtype="DenseSteelPlate" Count="200" />
      </Components>
      <CriticalComponent Subtype="KC_Component" Index="0" />
      <MountPoints>
        <MountPoint Side="Back" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Front" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Bottom" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Top" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Left" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
        <MountPoint Side="Right" StartX="0.1" StartY="0.1" EndX="0.9" EndY="0.9" />
      </MountPoints>
      <MirroringZ>Y</MirroringZ>
      <MirroringY>Z</MirroringY>
      <BuildProgressModels>
		<Model BuildPercentUpperBound="0.5" File="Models\Industrial_Centrifuge_Large_Constr2.mwm" />
		<Model BuildPercentUpperBound="1.0" File="Models\Industrial_Centrifuge_Large_Constr1.mwm" />
      </BuildProgressModels>
      <MountPoints>
	<MountPoint Side="Front" StartX="0.14" StartY="0.05" EndX="1.01" EndY="2.95" />
	<MountPoint Side="Back" StartX="2.00" StartY="0.01" EndX="2.96" EndY="2.99" />
	<MountPoint Side="Right" StartX="0.02" StartY="0.01" EndX="1.98" EndY="2.99" />
	<MountPoint Side="Bottom" StartX="0.09" StartY="0.13" EndX="2.95" EndY="1.87" />
	<MountPoint Side="Top" StartX="0.10" StartY="0.04" EndX="2.91" EndY="1.96" />
      </MountPoints>
      <BlockPairName>Hyperion_Fuel_Mixer</BlockPairName>
      <EdgeType>Light</EdgeType>
      <BuildTimeSeconds>100</BuildTimeSeconds>
      <DisassembleRatio>2.5</DisassembleRatio>
      <ResourceSinkGroup>Factory</ResourceSinkGroup>
      <InventoryMaxVolume>4</InventoryMaxVolume>
      <InventorySize>
        <X>2</X>
        <Y>2</Y>
        <Z>2</Z>
      </InventorySize>
      <StandbyPowerConsumption>0.001</StandbyPowerConsumption>
      <OperationalPowerConsumption>80</OperationalPowerConsumption>
      <BlueprintClasses>
	<Class>CoreReactor_Fuel</Class>
      </BlueprintClasses>
      <DamageEffectName>Damage_HeavyMech_Damaged</DamageEffectName>
      <DamagedSound>ParticleHeavyMech</DamagedSound>
      <PrimarySound>BlockAssembler</PrimarySound>
      <ActionSound>BlockAssemblerProcess</ActionSound>
      <DestroyEffect>Explosion_Missile</DestroyEffect>
      <DestroySound>WepSmallMissileExpl</DestroySound>
      <PCU>300</PCU>
    </Definition>`

**Comment by dorimanx** [comment]
<BlockPairName>Hyperion_Fuel_Mixer</BlockPairName>
not in config.. and was blocked from placing. and it's not just it, other blocks too.
like if not in config, then limit = 0
also there was no limit set at vanila config, and use vanila limits was not checked.

**Comment by dorimanx** [comment]
oooo! wait... this is Assembler and we have it limit = 1
this is a problem... how to deal with this?
many other blocks are refinery or gas generators, or other vanila things.. but they do something else..

**Comment by N1Ran** [comment]
you will need to make a limit using the subtypeIDs.  You can group them into one
