### ISSUE TITLE
GridType Limit "SmallGridsOnly" not functioning properly

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/BlockLimiter#18]
In my Misc LimitItems rules, the SmallGridsOnly filter does not appear to be applying properly.

I set a rule for SmallMissileLauncher TypeID which was intended for only applying to small grids, however it seems to be applying this rule to all grids, small and large (since the large grid version has the same TypeID). I also had this issue with another rule with turrets, although I was able to work around that by using the SubTypeID. This workaround is not possible for small grid SmallMissileLaunchers as they don't have a SubTypeID.

![image](https://user-images.githubusercontent.com/62247634/78511937-803fe380-776e-11ea-8209-a30ff31d3578.png)

**Comment by N1Ran** [comment]
Already working on this.  Notice the issue when while tracing another.  I missed a line during the update. Will be updated soon after testing.

**Comment by N1Ran** [comment]
updated.
