### ISSUE TITLE
Block limits keep bugging

### ISSUE THREAD

**Issue by CMDR-Koda** [N1Ran/BlockLimiter#19]
Using the BLockLimiter plugin it has recently been buggy, it keeps saying the limit is reached when it is not and only is fixed when i reenable the plugin - Plugin is up to date

**Comment by N1Ran** [comment]
Will need the config and limit in question to reproduce the issue.

**Comment by CMDR-Koda** [comment]
It's happening to all of the limits
`<?xml version="1.0" encoding="utf-8"?>
<BlockLimiterConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <LimitItems>
    <LimitItem>
      <Name>BARs Players</Name>
      <BlockList>
        <string>SELtdLargeNanobotBuildAndRepairSystem</string>
        <string>SELtdSmallNanobotBuildAndRepairSystem</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>3</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>BARs Factions</Name>
      <BlockList>
        <string>SELtdLargeNanobotBuildAndRepairSystem</string>
        <string>SELtdSmallNanobotBuildAndRepairSystem</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Large Refinery</Name>
      <BlockList>
        <string>LargeRefinery</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>6</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Blast Furnace</Name>
      <BlockList>
        <string>Blast Furnace</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>6</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>OxygenGeneratorSmall</Name>
      <BlockList>
        <string>OxygenGeneratorSmall</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>OxygenGenerator</Name>
      <BlockList>
        <string>OxygenGenerator</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>LargeAssembler</Name>
      <BlockList>
        <string>LargeAssembler</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>BasicAssembler</Name>
      <BlockList>
        <string>BasicAssembler</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Large Refinery Faction</Name>
      <BlockList>
        <string>LargeRefinery</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>20</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Blast Furnace Faction</Name>
      <BlockList>
        <string>Blast Furnace</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>20</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>OxygenGeneratorSmall Faction</Name>
      <BlockList>
        <string>OxygenGeneratorSmall</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>20</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>OxygenGenerator Faction</Name>
      <BlockList>
        <string>OxygenGenerator</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>20</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>LargeAssembler Faction</Name>
      <BlockList>
        <string>LargeAssembler</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>20</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>BasicAssembler Faction</Name>
      <BlockList>
        <string>BasicAssembler</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Elevator Top</Name>
      <BlockList>
        <string>VCZ_Elevator_Top</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>2</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Elevator Bottom</Name>
      <BlockList>
        <string>VCZ_Elevator_Bottom</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>2</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Gravel Sifter</Name>
      <BlockList>
        <string>Gravel Sifter</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Gravel Sifter Faction</Name>
      <BlockList>
        <string>Gravel Sifter</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>30</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Warhead</Name>
      <BlockList>
        <string>LargeWarhead</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>0</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
  </LimitItems>
  <ServerName>Block Limit</ServerName>
  <EnableLimits>true</EnableLimits>
  <EnableConvertBlock>false</EnableConvertBlock>
  <BlockOwnershipTransfer>false</BlockOwnershipTransfer>
  <MaxBlockSizeShips>0</MaxBlockSizeShips>
  <MaxBlockSizeStations>0</MaxBlockSizeStations>
  <MaxBlocksLargeGrid>0</MaxBlocksLargeGrid>
  <MaxBlocksSmallGrid>0</MaxBlocksSmallGrid>
  <UseVanillaLimits>false</UseVanillaLimits>
  <EnableLog>true</EnableLog>
  <Annoy>false</Annoy>
  <PunishInterval>300000</PunishInterval>
  <AnnoyMessage>You're in violation of set limits.  Use [!blocklimit mylimit] to view which limits you've exceeded</AnnoyMessage>
  <AnnoyInterval>300000</AnnoyInterval>
  <AnnoyDuration>15000</AnnoyDuration>
</BlockLimiterConfig>`

**Comment by N1Ran** [comment]
Issue identified.  Fix coming soon

**Comment by N1Ran** [comment]
Fix is up

**Comment by CMDR-Koda** [comment]
Thanks for the help :)
