### ISSUE TITLE
When running block limiter on large server above 400 grids, boot time is +5min more. 

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#22]
Hi
I am running latest build 1.6.806
3 servers using block limiter,
2 of them when starting stuck at point after patches, SIM is 0. no players, and just stay like this with constant 15%~20% CPU and just doing nothing for 5min. then keep going and booting.
All limits are fine, no crashes so far with trace to plugin.

And one server has 100+ grids, same limits as server 1, with 400+ grids, same plugins and same config!
but it's booting easy, as was before, max 3min.

Other 2 up to 8min boot...
Is there anything you can do for large servers? maybe run on different parallel thread and not block main?
Thanks.

**Comment by N1Ran** [comment]
The update already runs on a parallel thread. Can make it run less instructions per tick, but would make calculation take longer altogether, but should improve loadup and update.

**Comment by N1Ran** [comment]
I can only work on this issue if I have a world to test it on.  If you have such world, do share

**Comment by dorimanx** [comment]
Hi.
Here is save + blocklimiter config
https://www.dropbox.com/s/guofff45u394s28/2020-04-09%20173736.zip?dl=0

**Comment by N1Ran** [comment]
Fine tuned to not affect loadup time.  Update and let me know how it goes
