### ISSUE TITLE
Feature Request: Grid-size ranges for block limit rules

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/BlockLimiter#24]
Use Case:
I'd like to be able to create a rule where a small grid under 10 blocks has a limit of 2 turrets, and another rule where small grids greater than or equal to 11 blocks have a limit of 6 turrets.

**Comment by Bobothemonk** [comment]
This would be a cool feature, im sure it would be hard to do. But this would allow for larger ships to be more viable for sure. Instead of medium sized max turret boxes being the meta
