### ISSUE TITLE
essentials cleanup does not update player blocklimit count (but does update Gridlimit ones) 

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#26]
Blocklimiter v1.6.817
Copy of config : [BlockLimiter.txt](https://github.com/N1Ran/BlockLimiter/files/4522204/BlockLimiter.txt)

Steps to reproduce : 
Have blocklimiter configured
Place some blocks with creative. blocklimit mylimit updated as expected showing 3 drills in my test -- https://i.imgur.com/xVgD9u9.png
Run '!cleanup delete' to delete the drills (You can limit this command further to not just delete everything if you want - my test world just has no other grids I care about) - https://i.imgur.com/aDVVNpv.png

Running `!blocklimit update` does not update the player limit at this point either -- image taken after running update : https://i.imgur.com/9AGUP4e.png

edit - addition -- `!blocklimit update Kontu` also did not update the player blocklimits reported amounts either

**Comment by N1Ran** [comment]
Issue resolved in v1.6.818

**Comment by kontu** [comment]
Confirmed fixed in v1.6.818
