### ISSUE TITLE
Deleting blocks with creative tools using right click changes count by 3 instead of 1

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#27]
Blocklimiter v1.6.818
World set to Survival
Config - [BlockLimiter - Copy.txt](https://github.com/N1Ran/BlockLimiter/files/4529883/BlockLimiter.-.Copy.txt)

Place 10 drills using creative (10 drill limit set), looks good
https://i.imgur.com/Hq6UBXU.png

Delete 3 of them using right click in creative -- suddenly says I only have 1 in !blocklimit mylimit (should say 7)
https://i.imgur.com/jEOqasg.png 

Placed 2 more back, so I should have 9 (and do according to the GridLimit showing 1 on each grid)
PlayerDrillLimit said 3/10 (sorry didn't capture an image)

Because it only said 3, I was able to place a *bunch* more 
https://i.imgur.com/IDor1hS.png

Running "!blocklimit update" did update my limits in "!blocklimit mylimit"
https://i.imgur.com/sUGd3IM.png
https://i.imgur.com/Rgszfqr.png

I then used right click to remove *one* drill and now it says I have 14/10 when it should be 16/10 (and it does show 16 grids properly - so it appears to just be player limits being weird, not block limits
https://i.imgur.com/XMvONAx.png

Running "!blocklimit update" again corrected the reported PlayerDrillLimit to the expected 16/10 - just still no violation triggers

Did more testing - every time I remove a block w/ right click, it decreases the player limit count by 3 instead of 1.

**Comment by N1Ran** [comment]
fixed in v1.6.819

**Comment by kontu** [comment]
Confirmed fixed in v1.6.819
