### ISSUE TITLE
Limiting turrets easily

### ISSUE THREAD

**Issue by LordTylus** [N1Ran/BlockLimiter#3]
Hello there,

currently if you want to limit automated turrets you have to tediously add each and every BlockPair name to the config. Its fine for vanilla, but not so fine when also having modded turrets.

Since all Turrets most likely have the same base classes It would be neat if I could just say player X is only allowed 50 turrets. And he can combine them however he likes. 

Since my NoIdle Plugin seems to also set modded turrets to no idle it does not sound like that big of a problem I hope.

**Comment by N1Ran** [comment]
Added for next update.  You can now use blocktype by checking a box
