### ISSUE TITLE
Server crash with v1.6.819 pasting in a blueprint with limited blocks

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#30]
Blocklimiter v1.6.819
[BlockLimiter - Copy.txt](https://github.com/N1Ran/BlockLimiter/files/4530972/BlockLimiter.-.Copy.txt)

Tried pasting in a blueprint that had tiered tech drills on it, server crashed with the below error.
Tried two other different blueprints with drills (one had vanilla drills), same crash again.

I can use creative to place the drills no problem

None of the blueprints goes over the set 10 drill limit in Blocklimiter config and I have 

Crash1: https://pastebin.com/raw/Sjw3yGAY

Crash2: https://pastebin.com/raw/SctEdAQW

edit -- moved crash dumps to pastebin

**Comment by kontu** [comment]
There *is* a chance there are blocks missing from the world (modded blocks) that are in the blueprint, I haven't confirmed by do suspect that might be part of the trigger -- but it's certainly not the limited blocks that are missing

**Comment by N1Ran** [comment]
yea, it's going to be an easy fix.  Just need to add a null check

**Comment by N1Ran** [comment]
fixed in v1.6.821

**Comment by kontu** [comment]
Confirmed fixed in 1.6.821
