### ISSUE TITLE
Able to place beyond limit using creative control+drag or shift+drag

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#31]
v1.6.819

You'll...probably just tell me this is how life is and close this -- and that's fine by me if that's the case, but I wanted to report it *just* in case it's behavior you don't want

If I set a blocklimit, while it does stop me pasting in creative one by one; if I place them all at once while say, holding control to do a line, or control+shift to paste a planes worth it lets me put them all down
https://i.imgur.com/3MTD1oE.png

It does accurately update !blocklimit mylimit to show the correct number - it just doesn't prevent placement.
https://i.imgur.com/95Y7Yu2.png

**Comment by N1Ran** [comment]
v1.6.822

**Comment by kontu** [comment]
Confirmed fixed in 1.6.822
