### ISSUE TITLE
Feature Request: Add Exceptions with limits defined per IdentityId

### ISSUE THREAD

**Issue by SKO85** [N1Ran/BlockLimiter#34]
First of all, thanks for the plugin!

Would be nice to define Exceptions with not only the ID/Name, but also with an number for the limit. For example:

- Create a block limit for Drills per Player and set it to 12 (For all players).
- Add Exception for player A and limit to 0 (unlimited)
- Add Exception for player B and limit to 15

Kind of defining exceptions like in the HaE PBLimiter Plugin.

Cheers,
SKO

**Comment by N1Ran** [comment]
This level of exception is currently possible with current exception methods.
