### ISSUE TITLE
Rotor & Wheel Placement Cooldown?

### ISSUE THREAD

**Issue by CMDR-Koda** [N1Ran/BlockLimiter#35]
I noticed that the BlockLimiter plugin has added cooldowns to placing rotors and wheels.
Is there anyway I can disable this feature?
Couldn't find anything in the plugin menu or config file.
[Config.txt](https://github.com/N1Ran/BlockLimiter/files/4556673/Config.txt)

**Comment by N1Ran** [comment]
no such feature.  Prob another plugin.

**Comment by CMDR-Koda** [comment]
Alright thanks.
