### ISSUE TITLE
Feature Request : Ability to add block exceptions to a rule to handle overlapping TypeID's

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#36]
v.1.6.824
Say I have a server with the Nanobots build and repair mod. Type is "ShipWelder"; subtype is "SELtdLargeNanobotBuildAndRepairSystem"

I want to limit players to 10 *real* "ShipWelder" blocks and 1 "SELtdLargeNanobotBuildAndRepairSystem", as separate limits. But by setting up a player limit of 10 "ShipWelder"; the BuildandRepairSystem gets counted as one of the 10 "ShipWelder". Existing "exceptions" system is only for players/grids.

Let me know if anything isn't e

**Comment by kontu** [comment]
Supporting  "OxygenTank/LargeHydrogenTank" as a method to specificy both type and subtype in one line would help with this, but we'd still need exceptions for things like "OxygenTanks" which have a subtype of (Null)

**Comment by N1Ran** [comment]
I won't be added the block exception due to performance issue.  I can add support for the Type/Subtype since block definitions are written in that method which would be great for perf

**Comment by kontu** [comment]
Sure that will at least help some, thanks
