### ISSUE TITLE
Players reporting "Blocklimit reached" trying to paste in grids that don't even have limited blocks

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#37]
v1.6.822
[BlockLimiter - Copy.txt](https://github.com/N1Ran/BlockLimiter/files/4558860/BlockLimiter.-.Copy.txt)

We only limit Drills, Welders, Grinders, Refineries, Assemblers, 02/h2 gens, and Build and Repairs

Some players have tried pasting in blueprints that have none of these blocks  where they own 0 grids and are getting errors of "Block limit reached" (which is what we have the Deny message set to). Some players have tried to paste in a grid that is within limits and hit the same issue. Sometimes they try again a few hours later and it's fine. Running !blocklimit update doesn't allow them to suddenly paste it in though,

I would get the blueprints from them and it would paste in fine for me sometimes, and sometimes after a relog it would paste fine for them

Test server : It's a test server that at the time these were captured only had 17 grids on it total (including subgrids). We put Blocklimiter on for testing using the config in this ticket. There are no world block limits: https://i.imgur.com/XoO7RZE.png

Player 1: Owned 0 grids in the server. Tried to paste in a grid (this grid did include a single BuildandRepair), it failed to paste  giving them the deny message, and even though the grid wasn't in the world, their blocklimit mylimit claimed they had 1limited block. !blocklimit update did fix his limit counts afterwards : https://cdn.discordapp.com/attachments/703945792465141760/705134308028973117/unknown.png

Player 2: Owned 0 grids in the server. Tried to paste a grid that contained nothing but light armor and glass/window blocks -- got the deny message and it wouldn't paste in. https://cdn.discordapp.com/attachments/677538418741477386/705139922004082708/1041B724CFB02FC3900BB131203FEE49881D736D.png

Player 3: Did own some grids on the server with some assemblers / refineries / o2/h2 gens; but the grid they were pasting in had none of the blocks we limit on it -- https://cdn.discordapp.com/attachments/669214861053394945/705135725254934688/unknown.png

**Comment by kiozix** [comment]
Hi @kontu can you give me your config for bars i try to limit but not work 
thx
