### ISSUE TITLE
People saying block limit is reached when they havent

### ISSUE THREAD

**Issue by bodyboarder2528** [N1Ran/BlockLimiter#38]
00:01:25.8994 [INFO]   Torch.Managers.PluginManager: Loading plugin at BlockLimiter.BlockLimiter
00:01:25.8994 [INFO]   Torch.Managers.PluginManager: Loading plugin 'BlockLimiter' (v1.6.831)

Running latest version

Woke up this morning to complaints of blocklimits saying they was at limits when they wasnt.
This was reported by my moderator https://i.imgur.com/Un6MBTD.png  
![image](https://user-images.githubusercontent.com/49468427/82101627-53f58a80-9750-11ea-9d63-090453d9ef75.png)

**Comment by N1Ran** [comment]
sounds like they went over the limit.

**Comment by bodyboarder2528** [comment]
have another one now
https://cdn.discordapp.com/attachments/669266742446653471/711184506949861376/20200516215230_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711184516588240926/20200516215232_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711184522615717888/20200516215250_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711184532883243098/20200516215301_1.jpg
https://cdn.discordapp.com/attachments/669266742446653471/711186492604547152/20200516215707_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711186508190580817/20200516215717_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711186519053828146/20200516215812_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711186528889602128/20200516215821_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711186538951868466/20200516215844_1.jpg

https://cdn.discordapp.com/attachments/669266742446653471/711186548367949924/20200516215852_1.jpg

**Comment by bodyboarder2528** [comment]
and how does that work as it deletes one refinery and now he has none
![image](https://user-images.githubusercontent.com/49468427/82119429-d79b8f80-97c1-11ea-9e51-02df64f273cd.png)

**Comment by bodyboarder2528** [comment]
![image](https://user-images.githubusercontent.com/49468427/82119673-c05da180-97c3-11ea-86a9-bfcc4989aebe.png)
last shadow doesnt have any refineries yet it says he is at his limit

**Comment by N1Ran** [comment]
you may have that bug where builtby for NPCs is set to a player cause they share an ID with default NPC id.  He may not necessarily own them, but his id is attached to the block.  You'll need to either find one of the NPC grids or check the sandbox_0_0_0.sbs to find out.  The limiter is def reading ownership for that player.  The other way is to use PCU transferrer and search for authorship of grids

**Comment by bodyboarder2528** [comment]
do you have a command premade

**Comment by bodyboarder2528** [comment]
could hacking computer mod cause this?

**Comment by N1Ran** [comment]
only if he placed one on a grid and the ownership was transferred to him

**Comment by bodyboarder2528** [comment]
it should of hmmm

**Comment by bodyboarder2528** [comment]
im going to re enable it and test it also is it possible to maybe have a delete order as we used tiered tech and would rather it delete vanilla block first before the tiered tech ones if over limit?

**Comment by dorimanx** [comment]
limits are not updating per player/grid people reporting all the time that they have MORE than allowed.
even if they grind all, it's takes time till it's updated or server restart, OR manual update. by admin

**Comment by N1Ran** [comment]
count method updated.  Always triple check any reports and make sure players are not lying.  Command also added for players to update their limits.  Does have a 5min cooldown `!blocklimit update mylimit`

**Comment by bodyboarder2528** [comment]
possible to maybe have a delete order as we used tiered tech and would rather it delete vanilla block first before the tiered tech ones if over limit?
