### ISSUE TITLE
Admins Exception (global) still alert admins that they have overlimit!

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#39]
Hi.
Under Enable Logs there is Exceptio menu, i have set there all steam ID's of all admins.
We can place any blocks as expected.
And still can see that we have overlimit...

And Plugin still show us the Annoying Alert that we have overlimit...
Can you please correct this to not show alert.

Thanks.

**Comment by N1Ran** [comment]
Excepted players should not longer be annoyed
