### ISSUE TITLE
Allow Players to update their own limits with command!

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#40]
hi.

16:31:38.8210 [INFO]   CommandManager: Artika tried to use command blocklimit.update without permission
16:31:38.8210 [INFO]   Chat:  (to Artika): You need to be a Moderator or higher to use that command.

Please allow this to be used. or add a checkbox that allow or deny.
Auto update not working in time, as vanila does. people blowing up the discord with complains...

Thanks.

**Comment by N1Ran** [comment]
I can add this, but you do not want this access to player since it's an expensive method

**Comment by dorimanx** [comment]
there is not much of a choice... limits are not updating when removing blocks, so till i force update people stuck with x10 more limits than they actually have.

Please correct the code to instantly update the limit as vanila do, or allow players to update their limits so they will not say to remove this plugin as it's broken... 
We say NO Plugin stay!... but we must give them solution... or auto update, or command to fix their problems...

Thanks.

**Comment by RykerRus** [comment]
Can the way out of the situation be updating a specific limit?
For example !blocklimit Update limit=ProgramBlock

**Comment by N1Ran** [comment]
or give me full details on how to recreate the miscounts and the issue can be fixed completely.  Will be free later today to work on most of this issues and an update should be out by Sunday morning.  The more details I have would be wonderful

**Comment by N1Ran** [comment]
`!blocklimit update mylimit`
