### ISSUE TITLE
Adding your ship/base inside projector as blueprint, will count as placed blocks on grid.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#42]
Hi,
When loading projection of same ship to projector and turning that projecto OFF, blocklimiter show and alert! that we have X2 limits on that grid.
as all counter twice.
BP is part of the same grid. so all blocks in that BP counted as real blocks on that grid.

Please exclude all blocks loaded inside projection from limits counter.

Thanks.

**Comment by N1Ran** [comment]
already in progress

**Comment by N1Ran** [comment]
Projections count is now an option
