### ISSUE TITLE
Alternative output limits or copying text

### ISSUE THREAD

**Issue by RykerRus** [N1Ran/BlockLimiter#44]
Hello I play on a server where there are many limits on different blocks the current output of information does not allow you to quickly find the limit that interests me. I would like to be able to copy restrictions so that after inserting them into Notepad I can search for what I need.
P. S.
My solution to the issue in Fork.
To display limits on the LCD display, you need to:
1) hold the tool in your hand
2) Approach the open-access LCD display
3) register in the chat !blocklimit limits
4) Profit

The previous output also works.

**Comment by dorimanx** [comment]
https://github.com/RykerRus/BlockLimiter/commit/22462895bc8f79f88fd49436d29c417ca7794a81
