### ISSUE TITLE
it is possible to maybe have a delete order as we used tiered tech and would rather it delete vanilla block first before the tiered tech ones if over limit?

### ISSUE THREAD

**Issue by N1Ran** [N1Ran/BlockLimiter#45]
it is possible to maybe have a delete order as we used tiered tech and would rather it delete vanilla block first before the tiered tech ones if over limit?

_Originally posted by @bodyboarder2528 in https://github.com/N1Ran/BlockLimiter/issues/38#issuecomment-633323972_

**Comment by bodyboarder2528** [comment]
thanks

**Comment by bodyboarder2528** [comment]
Hey, idk if you have been working on this but if so is their a eta?

**Comment by N1Ran** [comment]
truthfully, it should be a quick change in list generated for punishment to sorted.  Just haven't had time to work on it.  I should sometime this weekend

**Comment by bodyboarder2528** [comment]
Ok sweet thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by N1Ran** [comment]
Added a method to run punishment on vanilla blocks first, but the effectiveness will depend on how fast blocks are being added and removed from the server
