### ISSUE TITLE
Possible Bug with grid convert blocking. servers are crashing!

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#46]
Hi,

I have set vanila max grid blocks 15000
and in limiter set 15K max for station, and 10K for ship.
And enabled the "grid convert blocking" checkbox. and restarted servers.

2 servers crash without logs, we had asked player to report what they do before server crash,
And turn out that players covert station to ship and bam... happens to random players,
But same thing, convert to ship, and crash, no crash logs...

For now i have disabled and set limit to 10K on both.

Please check if something can be checked to prevent crash.

Thanks.

**Comment by dorimanx** [comment]
Also small request, please update the https://github.com/N1Ran/BlockLimiter/wiki/Commands
with new command for updating limits by players.
!blocklimit update mylimit
command is working perfectly!!! really helpful and resolved countless complains about limits not updated in time.
Players fix their limits easy!

**Comment by N1Ran** [comment]
unable to reproduce bug
