### ISSUE TITLE
BUG: When admin is in global exclude list, he is still affected by punishment.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#48]
Hi,

All blocks that owned by admins in global exclude are deleted by plugin.
When punishment is enabled.

Admins dont see any over limit alerts, blocks deleted as for all other players if they are over limited.

Please correct.
Thank you.

**Comment by N1Ran** [comment]
if you just added the admin, their already set for punishment blocks won't be removed except if you run a reload command

**Comment by N1Ran** [comment]
Also, if the limit as faction enabled and admin is a faction that went over the limit, They will still be punished.  You can add faction tags to exception too if this seems to be the case

**Comment by dorimanx** [comment]
no, admins all added at first stages of configuration.
all limits are player or grid only. no faction limits.

First admins were getting the overlimit alerts, you have fixed that, now there are no alerts but blocks are deleted.

**Comment by N1Ran** [comment]
That's odd.  Same check is used for punishment.  I can't reproduce this neither.  Did you check the names and make sure there's no spelling error or wrong Id used?

**Comment by dorimanx** [comment]
Spelling is correct i have used steam IDS in Global Exception tab.
I have ship with overlimit in per grid weapons.
each time i login, i am missing guns.
And i can place as many as i want, so exception works as should. and i have no warning that each player see every 10min.
but blocks are deleted.
when timer of 58min to panishment is reached.

**Comment by N1Ran** [comment]
fixed
