### ISSUE TITLE
Punishment will delete more blocks than should if overlimit found. 

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#49]
Hi

Players reporting that they had 4 blocks of nanodrills on grid, and we have set 2 max, and enabled punishment.

we expected that only 2 blocks will be deleted, but plugin deleted all 4.

Please see if that can be fixed.

Thank you.

**Comment by N1Ran** [comment]
do you have the limit setting causing this?

**Comment by dorimanx** [comment]
Yes, i am working with subtype only! there are no Types in limits.

`
    <LimitItem>
      <Name>NanobotBuildAndRepairSystem</Name>
      <BlockList>
        <string>SELtdLargeNanobotBuildAndRepairSystem</string>
        <string>SELtdSmallNanobotBuildAndRepairSystem</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
`

**Comment by dorimanx** [comment]
`
    <LimitItem>
      <Name>NanobotDrillSystem</Name>

      <BlockList>
        <string>SELtdLargeNanobotDrillSystem</string>
        <string>SELtdSmallNanobotDrillSystem</string>
      </BlockList>

      <BlockPairName />
      <Exceptions />

      <Limit>2</Limit>

      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>

      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
`

**Comment by N1Ran** [comment]
Can't reproduce this.  I need more details to how they manage to get the limit to count 4 more than they have.

**Comment by dorimanx** [comment]
Player had 2 nanodrills on grid.
sent it to garage (plugin to store grind to files)
server crashed, and on rollback player got his ship in world, and 1 in garage.
Then he pulled stored grid from garage.

Now he has 2 ships with 4 blocks, and overlimit of 4/2 nanodrills.
After 58min all 4 blocks are deleted.

**Comment by N1Ran** [comment]
so, I don't have access to the garage plugin.  Can you test the following and report the results please.

*Run `!blocklimit mylimit`, screenshot this
*Build a grid with some limited blocks
*Run `!blocklimit mylimit`, screenshot this
*Save the grid to garage
*Run `!blocklimit mylimit`, screenshot this
*Restore the grid from garage
*Run `!blocklimit mylimit`, screenshot this

**Comment by dorimanx** [comment]
I have tested as you asked, and i see that limits are counted as expected now, before and after garage use.
[http://www.dorimanx.com/temp/Space/Capture-Before.JPG](url)
[http://www.dorimanx.com/temp/Space/Capture-in-garage.JPG](url)
[http://www.dorimanx.com/temp/Space/Capture-from-garage-out.JPG](url)

**Comment by dorimanx** [comment]
I guess you can close this isse, thanks.
