### ISSUE TITLE
Possible Issue with Projection Count function:

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#51]
Hi,

Our players reporting dual limits once they load projection on their ship to repair it.
Projection is the same as ship just full.

So what i have seen, player has limit of 0/8 shield blocks.
Then he enable projector with same grid loaded just with 8 shield blocks.

I have set limit. 8 shield blocks per player and per grid! same config.

`

    <LimitItem>
      <Name>Shield HighTech</Name>
      <BlockList>
        <string>LargeShipSmallShieldGeneratorBase</string>
        <string>SmallShipSmallShieldGeneratorBase</string>
      </BlockList>
      <BlockPairName />
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>true</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
`

Count Projection is ON.

Player see in !blocklimit mylimit

16/8 per player
8 on grid "NAME"
Player run !blocklimit update mylimit
Still the same.

If he disable projector, and do !blocklimit update mylimit
all limits are normal. 0 shield blocks build by this player. and nothing for grid.

I have disabled Projection Count. and now all as should be.
limits are 8/8 player and 8 on his grid.

Please check this function.

Thank you :)

**Comment by N1Ran** [comment]
sounds like it's doing what it should

**Comment by dorimanx** [comment]
well not really. player dont have any blocks, then he enable projector, and get limit x2 and should have only 1 limit on him.
without projector count option, he get the exact amount of blocks in his limit when they are projected.

**Comment by N1Ran** [comment]
ok, that does sound like a bug.  Will check
