### ISSUE TITLE
Feature request : Apply punishment (or just force to off) to limited blocks ownedby "Nobody"

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#52]
Asked via discord -- Is there a way to have blocklimiter force any blocks owned by Nobody to off (even if it's under the normal punishment timer) ? 

I don't think it needs to do the full blown punishment I think that'd be messy if someones using explode or whatnot, but at least forcing them to off would help cheese preventing

**Comment by N1Ran** [comment]
added
