### ISSUE TITLE
Request: Add PCU limit value! same as blocks.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#55]
Hi,

I like to ask to add a possible PCU amount on one grid option.

Some players build 1 Dynamic Grid, with much more PCU that we allow,
We have 100K PCU for each player, and we want to enforce this limit on one grid.

But it's not possible.

Please add such limit enforcement.

Thank you.

**Comment by N1Ran** [comment]
PCU limiter plugin by SKO
https://torchapi.net/plugins/item/589f0698-d9c2-4d7c-b4fb-64df67657fcd
