### ISSUE TITLE
Blocklimiter not detecting players over the limit

### ISSUE THREAD

**Issue by IgneusTempus** [N1Ran/BlockLimiter#57]
this is my first time im posting anything like this. Im a total noob just trying to help and make my players not abuse the limits

[Torch-2020-07-07 - Copy.log](https://github.com/N1Ran/BlockLimiter/files/4886538/Torch-2020-07-07.-.Copy.log)

**Comment by N1Ran** [comment]
I will need more details on this matter.  Post your `BlockLimiter.cfg` and which of the limit is not being counted.  Also, if punishment is set to delete/destroy, you'll rarely notice overcounts.

**Comment by IgneusTempus** [comment]
does not support the CFG file.

<?xml version="1.0" encoding="utf-8"?>
<BlockLimiterConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <LimitItems>
    <LimitItem>
      <Name>Mining Drills</Name>
      <BlockList>
        <string>Drill</string>
        <string>Drill2x</string>
        <string>Drill4x</string>
        <string>Drill8x</string>
        <string>SELtdNanobotDrillSystem</string>
      </BlockList>
      <Exceptions />
      <Limit>12</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Welder</Name>
      <BlockList>
        <string>ShipWelder</string>
        <string>ShipWelder2x</string>
        <string>ShipWelder4x</string>
        <string>ShipWelder8x</string>
      </BlockList>
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Grinders</Name>
      <BlockList>
        <string>ShipGrinder</string>
        <string>ShipGrinder2x</string>
        <string>ShipGrinder4x</string>
        <string>ShipGrinder8x</string>
      </BlockList>
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>AtlasSuperLaser</Name>
      <BlockList>
        <string>WL_SuperLaser</string>
      </BlockList>
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>DronePod</Name>
      <BlockList>
        <string>SGDronePod</string>
      </BlockList>
      <Exceptions />
      <Limit>2</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Nanites</Name>
      <BlockList>
        <string>NaniteControlFacility</string>
      </BlockList>
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>BuildAndRepair</Name>
      <BlockList>
        <string>SELtdNanobotBuildAndRepairSystem</string>
      </BlockList>
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>SafeZone</Name>
      <BlockList>
        <string>SafeZone</string>
      </BlockList>
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>true</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>M2 Missile</Name>
      <BlockList>
        <string>M2Destroyer</string>
      </BlockList>
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>M1 Missile</Name>
      <BlockList>
        <string>M1Torpedo</string>
      </BlockList>
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>M8 Missile</Name>
      <BlockList>
        <string>M8Launcher</string>
      </BlockList>
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>M12 Missile</Name>
      <BlockList>
        <string>M12Swarm</string>
      </BlockList>
      <Exceptions />
      <Limit>10</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Defense Turrets</Name>
      <BlockList>
        <string>MA_PDX</string>
        <string>TelionAMACM</string>
        <string>TelionAF</string>
        <string>TelionAFGen2</string>
        <string>MA_PDT</string>
        <string>EX1PointDefense</string>
        <string>EXODPointDefense</string>
        <string>HeavyDefenseTurret</string>
      </BlockList>
      <Exceptions />
      <Limit>20</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Gladius Laser</Name>
      <BlockList>
        <string>MA_Gladius</string>
      </BlockList>
      <Exceptions />
      <Limit>4</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Flares</Name>
      <BlockList>
        <string>FlareLauncher</string>
      </BlockList>
      <Exceptions />
      <Limit>2</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>true</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Main Weapons</Name>
      <BlockList>
        <string>XB3BeamBattery</string>
        <string>XB3PulseBattery</string>
        <string>X3HB</string>
        <string>RailgunxTurret</string>
        <string>BattleshipCannonMK3</string>
        <string>MCRNRailGun</string>
        <string>BFG_M</string>
      </BlockList>
      <Exceptions />
      <Limit>5</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Secondary Weapons</Name>
      <BlockList>
        <string>BattleshipCannonMK2</string>
        <string>BattleshipCannonMK22</string>
        <string>RailgunxTurretM</string>
        <string>BattleshipCannon</string>
      </BlockList>
      <Exceptions />
      <Limit>4</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Small Weapons</Name>
      <BlockList>
        <string>MA_Meatball_Base</string>
        <string>MA_Blister</string>
        <string>MA_Gimbal_Laser_Armored</string>
        <string>MA_Gimbal_Laser_Armored_Slope</string>
        <string>MA_Gimbal_Laser_Armored_Slope2</string>
        <string>MA_Gimbal_Laser_Armored_Slope45</string>
        <string>MA_Gimbal_Laser</string>
        <string>XB1BeamBattery</string>
        <string>XB1PulseBattery</string>
        <string>RailgunxTurretS</string>
      </BlockList>
      <Exceptions />
      <Limit>8</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Fixed Weapons</Name>
      <BlockList>
        <string>TelionBattery1</string>
        <string>TelionBattery1Stack</string>
        <string>MK1_Battery</string>
        <string>MA_Fixed_000</string>
        <string>MA_Fixed_001</string>
        <string>MA_Fixed_002</string>
        <string>MA_Fixed_003</string>
        <string>MA_Fixed_004</string>
        <string>MA_Fixed_005</string>
        <string>MA_Fixed_006</string>
        <string>MA_Fixed_007</string>
        <string>EX1BeamCannon</string>
        <string>MA_Tiger</string>
        <string>MA_Tiger_30</string>
        <string>Railgunx75f</string>
        <string>Railgunx150f</string>
      </BlockList>
      <Exceptions />
      <Limit>12</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <Name>Harpoon</Name>
      <BlockList />
      <Exceptions />
      <Limit>1</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>true</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>DeleteBlock</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>true</RestrictProjection>
    </LimitItem>
    <LimitItem>
      <BlockList />
      <Exceptions />
      <Limit>0</Limit>
      <LimitFaction>false</LimitFaction>
      <GridTypeBlock>AllGrids</GridTypeBlock>
      <LimitGrids>false</LimitGrids>
      <LimitPlayers>false</LimitPlayers>
      <Punishment>None</Punishment>
      <IgnoreNpcs>false</IgnoreNpcs>
      <RestrictProjection>false</RestrictProjection>
    </LimitItem>
  </LimitItems>
  <MaxBlocksSmallGrid>0</MaxBlocksSmallGrid>
  <MaxBlocksLargeGrid>0</MaxBlocksLargeGrid>
  <MaxBlockSizeShips>30000</MaxBlockSizeShips>
  <MaxBlockSizeStations>0</MaxBlockSizeStations>
  <EnableLimits>true</EnableLimits>
  <ServerName>BlockLimiter</ServerName>
  <DenyMessage>Limit reached</DenyMessage>
  <ProjectionDenyMessage>{BC} blocks removed from projection due for going over limit</ProjectionDenyMessage>
  <EnableConvertBlock>true</EnableConvertBlock>
  <BlockOwnershipTransfer>false</BlockOwnershipTransfer>
  <MergerBlocking>false</MergerBlocking>
  <UseVanillaLimits>false</UseVanillaLimits>
  <GeneralException>
    <string>Igneus Tempus</string>
  </GeneralException>
  <CountProjections>true</CountProjections>
  <KillNoOwnerBlocks>false</KillNoOwnerBlocks>
  <LogFileName>BlockLimiter-${shortdate}.log</LogFileName>
  <Annoy>true</Annoy>
  <PunishInterval>300</PunishInterval>
  <AnnoyMessage>You're in violation of set limits.  Use [!blocklimit mylimit] to view which limits you've exceeded</AnnoyMessage>
  <AnnoyInterval>300</AnnoyInterval>
  <AnnoyDuration>15000</AnnoyDuration>
</BlockLimiterConfig>

**Comment by N1Ran** [comment]
in your logs folder, find the file that is named `BlockLimit***.log` and post it here

**Comment by IgneusTempus** [comment]
[BlockLimiter-2020-07-07.log](https://github.com/N1Ran/BlockLimiter/files/4888408/BlockLimiter-2020-07-07.log)
there

**Comment by N1Ran** [comment]
looks like it's blocking players from placing blocks just fine and annoying them as should when they go over.  It should also punish around same time it's annoying the player base on your settings, but it's not.

**Comment by kontu** [comment]
We're seeing similar with player limits (grid limits work fine) but if a player relogs it updates their count correctly and correctly blocks them after that. BlockLimiter logs look completely normal (no errors no nothing). Torch log has 0 messages relating to it either. I'll try to record video later to show

**Comment by N1Ran** [comment]
I need to know specific details on how to recreate the issue.  Players come up with ways to trick limits and the previous way to avoid this was to constantly update the count which was not performance friendly.  You can use autocommands to trigger updates (not recommended) or provide details to how players are tricking the limiter and I can block it from that level

**Comment by kontu** [comment]
I *think* the way we had players end up with this is similar to the method in issue 61 -- after 61 gets fixed I'll keep another eye out to see if this comes up for us again
