### ISSUE TITLE
Was unable to cut and paste an existing grid, can not determine why

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#58]
We are currently only using Gridlimits on our servers (no player or faction limits) and last night had a grid that was in-compliance need an admin cut and paste; but Blocklimiter wouldn't let us paste it back in

Logs didn't tell us why - but ultimately the staff member went and remove a personal grid of his that had some refineries, and then he was able to paste the problem players grid in fine

Nothing showing up in blocklimit violations

Attached is zip of blocklimiter config, a gridbackup sbc of the grid we were trying to cut and paste, and the blocklimiter log file
[2020_07_07_22_44_01.zip](https://github.com/N1Ran/BlockLimiter/files/4892735/2020_07_07_22_44_01.zip)

**Comment by kontu** [comment]
There is a projector on that grid, but we have "CountProjections" set to false so I wouldn't expect it to get in the way, it was also turned off at the time.

**Comment by N1Ran** [comment]
spawn method changed just remove affected blocks

**Comment by kontu** [comment]
That's...somewhat undesired as it shouldn't have been blocking in the first place in this instance; and would cause more work for server admins figuring out what blocks a player is suddenly missing after a cut and paste (or fixship) if block counts are off or not working correctly for any reason

Any chance to hook the spawn method decision into the punishment type choices as a config? Because we only punish by powering off, not removing.
