### ISSUE TITLE
Bug: Cannot Detect a Station from a Ship.

### ISSUE THREAD

**Issue by JemiloII** [N1Ran/BlockLimiter#60]
I have been trying out the different Grid types. If you set Ship limits, it will limit the Stations.

I run a server where we don't allow refineries on ships and only 1 assembler on a single military ship. Setting `ShipOnly`, checking `Grids`, and setting the limit to 0 or 1 forces station grids to those limits. I've also tried setting Large grids for drills to 2, however, it wasn't allowing the small grids drill limit of 4; instead, forcing it to 2.

**Comment by N1Ran** [comment]
Can I get your BlockLimiter.cfg and also with of the limit is causing said issue
