### ISSUE TITLE
Blocklimiter does not update grinded/destroyed blocks until restart.

### ISSUE THREAD

**Issue by ilgmars** [N1Ran/BlockLimiter#61]
Block limiter does not update ground/destroyed blocks until restart or manual update via command.
attached logs.
[BlockLimiter-2020-08-03.log](https://github.com/N1Ran/BlockLimiter/files/5035395/BlockLimiter-2020-08-03.log)
[BlockLimiter-2020-08-04.log](https://github.com/N1Ran/BlockLimiter/files/5035396/BlockLimiter-2020-08-04.log)
[BlockLimiter-2020-08-05.log](https://github.com/N1Ran/BlockLimiter/files/5035397/BlockLimiter-2020-08-05.log)
[BlockLimiter-2020-08-06.log](https://github.com/N1Ran/BlockLimiter/files/5035398/BlockLimiter-2020-08-06.log)
[Keen-2020-07-29.log](https://github.com/N1Ran/BlockLimiter/files/5035399/Keen-2020-07-29.log)
[Keen-2020-07-30.log](https://github.com/N1Ran/BlockLimiter/files/5035400/Keen-2020-07-30.log)
[Keen-2020-07-31.log](https://github.com/N1Ran/BlockLimiter/files/5035401/Keen-2020-07-31.log)
[Keen-2020-08-01.log](https://github.com/N1Ran/BlockLimiter/files/5035402/Keen-2020-08-01.log)
[Keen-2020-08-02.log](https://github.com/N1Ran/BlockLimiter/files/5035404/Keen-2020-08-02.log)
[Keen-2020-08-03.log](https://github.com/N1Ran/BlockLimiter/files/5035405/Keen-2020-08-03.log)
[Keen-2020-08-04.log](https://github.com/N1Ran/BlockLimiter/files/5035406/Keen-2020-08-04.log)
[Keen-2020-08-05.log](https://github.com/N1Ran/BlockLimiter/files/5035407/Keen-2020-08-05.log)
[Keen-2020-08-06.log](https://github.com/N1Ran/BlockLimiter/files/5035408/Keen-2020-08-06.log)
[Torch-2020-07-29.log](https://github.com/N1Ran/BlockLimiter/files/5035409/Torch-2020-07-29.log)
[Torch-2020-07-30.log](https://github.com/N1Ran/BlockLimiter/files/5035410/Torch-2020-07-30.log)
[Torch-2020-07-31.log](https://github.com/N1Ran/BlockLimiter/files/5035411/Torch-2020-07-31.log)
[Torch-2020-08-01.log](https://github.com/N1Ran/BlockLimiter/files/5035412/Torch-2020-08-01.log)
[Torch-2020-08-02.log](https://github.com/N1Ran/BlockLimiter/files/5035413/Torch-2020-08-02.log)
[Torch-2020-08-03.log](https://github.com/N1Ran/BlockLimiter/files/5035414/Torch-2020-08-03.log)
[Torch-2020-08-04.log](https://github.com/N1Ran/BlockLimiter/files/5035415/Torch-2020-08-04.log)
[Torch-2020-08-05.log](https://github.com/N1Ran/BlockLimiter/files/5035416/Torch-2020-08-05.log)
[Torch-2020-08-06.log](https://github.com/N1Ran/BlockLimiter/files/5035419/Torch-2020-08-06.log)
[BlockLimiter-2020-07-29.log](https://github.com/N1Ran/BlockLimiter/files/5035420/BlockLimiter-2020-07-29.log)
[BlockLimiter-2020-07-30.log](https://github.com/N1Ran/BlockLimiter/files/5035421/BlockLimiter-2020-07-30.log)
[BlockLimiter-2020-07-31.log](https://github.com/N1Ran/BlockLimiter/files/5035422/BlockLimiter-2020-07-31.log)
[BlockLimiter-2020-08-01.log](https://github.com/N1Ran/BlockLimiter/files/5035423/BlockLimiter-2020-08-01.log)
[BlockLimiter-2020-08-02.log](https://github.com/N1Ran/BlockLimiter/files/5035424/BlockLimiter-2020-08-02.log)

**Comment by kontu** [comment]
We had a player grind down their build and repair - limited per grid only, not per player
https://i.imgur.com/2XaCvYQ.png

But they can't place it back (same grid they ground it off on)
https://i.imgur.com/Vkelv2d.png

List of blocks on grid by subtype:
Blocks in World
```
78 LargeBlockArmorBlock
23 LargeBlockArmorSlope
22 Window1x1Face
14 Window1x1Inv
12 Window1x1Slope
12 LargeBlockSolarPanel
10 ConveyorTube
10 LargeBlockArmorCorner
7 LargeBlockArmorSlope2Base
6 LargeBlockArmorCornerInv
6 LargeBlockArmorSlope2Tip
5 ConveyorTubeCurved
4 Window1x1Side
2 LargeBlockBatteryBlock
2 AQD_LG_ConveyorT
2 SmallLargeHydrogenTank
2
2 SmallLight
2 GratedStairs
2 AQD_LG_ConveyorStraightArmored
2 LargeShipMergeBlock
1 CatwalkStraight
1 Connector
1 CockpitOpen
1 LargeBlockCorner_LCD_1
1 RotaryAirlock
1 LargeBlockBathroom
1 LargeRefinery2x
1 LargeBlockDeskChairlessCorner
1 LargeBlockLargeContainer
1 LargeAssembler2x
1 LargeBlockBed
1 Window1x1FlatInv
1 LargeBlockSmallContainer
1 LargeBlockKitchen
1 SurvivalKitLarge
1 LargeHydrogenEngine
1 LargeBlockDeskCorner
1 CatwalkWall
1 RotatingLightLarge
1 AQD_LG_ConveyorTArmored
1 AQD_LG_ConveyorCornerArmored
1 Window1x1Flat
1 LargeBlockConveyor
1 LargeBlockBeacon

Total: 249 Blocks

1 Grids checked
```

Running a `;; blocklimit update "-grid=MMT_MainStation 02"` on the grid resolved the issue for the player.
Blocklimiter logs have no errors, just info messages. Torch logs show nothing wrong either

**Comment by N1Ran** [comment]
There might be another factor causing this cause I can't reproduce.  Also, I'll suggest using the {BL} variable to list blocks in question when it's blocked.  There could be a chance it's another limit causing the denial entirely instead of the BaR. Also, post your config cause if you have a limit for shipwelders and the player already maxed out on that, BaR will also be denied.

**Comment by kontu** [comment]
After next reboot I'll get more data (added better bc/bl variables in our messaging on the main server we see the issue). For me, I just build 5 armor blocks, placed 5 ShipGrinders, ground them off, placed 5 more and my limit counts were wonky for both grid and player.

Let me video and more and I'll pop the config and everything in here hopefully...today

**Comment by kontu** [comment]
Hah found a way to reliably reproduce for us

https://youtu.be/_WJEF_skovA

**Comment by N1Ran** [comment]
The grid update was re adding the blocks since it's delayed

**Comment by kontu** [comment]
Had a player grind a grid apart into two halves on v1.6.877 (SEC HydroShip) and now their grid count is still 
ProductionGrid is configured for:
```Blast Furnace
LargeRefinery
LargeRefinery2x
LargeRefinery4x
LargeRefinery8x
BasicAssembler
LargeAssembler
LargeAssembler2x
LargeAssembler4x
LargeAssembler8x
OxygenGenerator
```

All blocks on the grid:
```Blocks in World
544 LargeBlockArmorBlock
140 LargeSteelCatwalkPlate
39 AQD_LG_ConveyorStraightArmored
26
19 LargeBlockSmallHydrogenThrust
13 Window1x1FlatInv
11 LargeBlockArmorSlope
11 AQD_LG_ConveyorXArmored
9 Window1x1Slope
8 SmallLight
7 AQD_LG_ConveyorCornerArmored
6 LargeBlockArmorCornerInv
6 AQD_LG_ConveyorTArmored
5 LargeBlockDrill
5 LargeBlockLandingGear
4 LargeBlockFrontLight
4 LargeProductivityModule
4 Suspension5x5
4 LargeEnergyModule
4 Suspension5x5mirrored
4 LargeBlockLight_1corner
4 LargeBlockOffsetDoor
4 LargeBlockGyro
3 LargeBlockLargeHydrogenThrust
3 LargeHydrogenTank
3 LargeBlockBatteryBlock
3 LargeStairs
2 LargeBlockArmorCorner
2 LargeDecoy
2 Window1x1Face
2 LargeHydrogenEngine
2 LargeShipWelder
2 LargeAssembler
2 LargeBlockCockpitSeat
1 LargeOreDetector
1 CropGrower
1 LargeRefinery
1 LargeBlockRemoteControl
1 LargeBlockLargeContainer
1 Hydroponics
1 Kitchen
1 WRS
1 SurvivalKitLarge
1 LargeBlockBeacon
1 Connector

Total: 918 Blocks

1 Grids checked
```
but blocklimiter thinks the grid has 28. Grinding/adding doesn't change the number
https://i.imgur.com/MQx5duE.png

Running a manual update on the grid corrected its limits
https://i.imgur.com/nXpDvD9.png

So might still be something hinky in the grid update?

**Comment by N1Ran** [comment]
need more details on the grid and can this be reproduced? A video would be great if you can

**Comment by kontu** [comment]
Using the same method in the previous video
https://youtu.be/_WJEF_skovA

https://i.imgur.com/KqED66I.png
There are only 6 refineries total; but it thinks one grid has 10 for some reason (it has 5); and the other has 1 (correct)

https://i.imgur.com/Z69CeZi.png
