### ISSUE TITLE
Request/Bug?: gridLimit violation have no warning included

### ISSUE THREAD

**Issue by scytero** [N1Ran/BlockLimiter#64]
When violating a grid-based limit (that should not be possible, btw.), there is no warning created for the owning and/or acting player(s). Instead, only the reaction gets fired later on (e.g. shutting off, deteting or exploding the block(s)).

If this is intentional, I request adding a warning via notification and/or chat, to inform players of the violation on a grid they own, independently of "handling" the block.

**Comment by N1Ran** [comment]
That is the annoyance system.  You'll need to enable it for it to function.  As for message to owner when punishment is issued, there's one now but it's done during punishment trigger.  I'll suggest having your warning at shorter interval to punishment

**Comment by scytero** [comment]
Annoyance system is enabled and active, still there is no indicator when going over the grid limits.
