### ISSUE TITLE
Feature Request: Additional variable for messaging

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#65]
https://github.com/N1Ran/BlockLimiter/issues/32 added in {BC} and {BL} which have been helpful keeping players informed on what blocks are hitting limits - however in an environment where one block may be specified under differently named limits it lacks some information on why they are being blocked

Would you please consider a third variable that printed the name of the limit that's causing the restriction?
https://i.imgur.com/DbluU4I.png

**Comment by N1Ran** [comment]
{L}  added as variable to display limit.  This is still in development and may display the wrong limit when the reason is due to grid size violation
