### ISSUE TITLE
[1.6.8] Block counter not decreasing

### ISSUE THREAD

**Issue by scytero** [N1Ran/BlockLimiter#7]
When placing a new block, the block counter towards a player's limit is increasing, but not decreased after the block got removed. This results in playerlimits stacking up indefinitely on building and the automatic routines being triggered due to a limit violation (that actually is not there). 
Still, the player is able to place a new block while the actual blockcount is within the set limits.

* is there a handle for `onBlockRemoved`/ `onBlockDestroyed`added, decreasing the limit?
* would it be an option, to update the player's blocklist also while he is building, as the placement-prevention seems to work correctly.

**Comment by Isadorious** [comment]
Getting this issue as well. Also, this has caused a large amount of log spam with logging set to on

**Comment by N1Ran** [comment]
1.6.801 should've fixed this. Can you give me a snippet of the log Isadorious

**Comment by dorimanx** [comment]
Hi, sadly same issue, blocks are added, but not removed. and cleaned by delete.
https://cdn.discordapp.com/attachments/689536240214605864/689572765614735388/unknown.png

**Comment by N1Ran** [comment]
1.6.801 has a fix for this issue.  Update and let me know if you're still experiencing this
