### ISSUE TITLE
Huge sim loss / broken counts in latest version (v1.7.014)

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#72]
Huge sim loss / broken counts in latest version (v1.7.014)

Everything just kept counting up forever
https://i.imgur.com/cOJ1N8y.png
https://cdn.discordapp.com/attachments/301835879947698177/778325521917804544/BlockLimiter-2020-11-17.log

[torchlog.txt](https://github.com/N1Ran/BlockLimiter/files/5555499/torchlog.txt)

Had to !blocklimit enable false to stop the huge sim loss

**Comment by DionisioVega82** [comment]
might I ask how you have the config set up to limit the blocks on your server? So far it is ignoring all of the block entries I have entered into the blocklimit section and since I cannot find any examples of how to enter the information properly, an example is greatly appreciated.
