### ISSUE TITLE
adding the option for blocklimiter to be able to see all ingame blocks when server is running

### ISSUE THREAD

**Issue by bodyboarder2528** [N1Ran/BlockLimiter#74]
how likely are you to the idea of adding the option for blocklimiter to be able to see all ingame blocks when server is running so it will be easier to select the block u want limited like what foogs did with rewards
![image](https://user-images.githubusercontent.com/49468427/102146766-af8e1f00-3ebd-11eb-995c-50da5c299d96.png)

**Comment by N1Ran** [comment]
not planning on working on this since Torch will eventually lose its UI
