### ISSUE TITLE
Request to add per grid checks on subgrids too.

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#75]
Hi, right now if we use per grid limits, all connected to grid subgrids counted as new grid with new limit.
This allows people to create overlimit grids and destroy the balance that we are trying to create.

Please add check that will count all blocks including connected by mechanical parts (exclude the connectors as this will lead to bad things)
And if over limit then use the punishment system for what ever set there.

Thanks.

**Comment by N1Ran** [comment]
This check should be active on current build.
