### ISSUE TITLE
Feature Request: Chat warning for overgrid limits

### ISSUE THREAD

**Issue by Fowlplaychiken** [N1Ran/BlockLimiter#76]
Would like to set a limit of 4 large grids per player, which block limiter can do. However, I very much dislike "hard" enforcement like what block limiter does now. Rather than preventing more grids, or turning stuff off, or deleting it, I would rather the "punishment" just be a public chat warning for all to see, announcing the name and faction of the player who is over  limits. If its over limits for long, I will go manually enforce it as admin  I think this may exist already for 'block over limit', although unsure its public? But it does not exist as option for grid over limit.

**Comment by N1Ran** [comment]
feature added
