### ISSUE TITLE
[1.6.8] Filters dissapearing in lists

### ISSUE THREAD

**Issue by scytero** [N1Ran/BlockLimiter#8]
Whenever the selection dropdown "Use BuiltBy" gets changed, eventually the entries of the respective filter in lists (violations, mylimits, ...) is missing afterwards, until the plugin gets disabled and enabled again. The log tells, that the configuration got saved.

I did not check for other options so far.

**Comment by dorimanx** [comment]
i can confirm this.
my limits show all right after that limit, but all above that limit is missing.

**Comment by N1Ran** [comment]
1.6.801 already fixed that issue

**Comment by N1Ran** [comment]
I can't seem to reproduce this issue
