### ISSUE TITLE
Blocking projections when it shouldn't

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/BlockLimiter#81]
I was attempting to project a ~200 block ship that is well under the 10000 block limit, but every time it would block the projection entirely. I get the Deny Message in chat, and *sometimes* the log shows `22:09:22.8393 [INFO]   Projection blocked from Mike Dude due to size limit`. Restrict Projection is also disabled on every limit. This is happening to multiple players and persisting over restarts. This leads me to believe the grid limit block limit check for projections is incorrect. This only appeared with the latest version 1.7.103.

![image](https://user-images.githubusercontent.com/62247634/111497976-2af2ad00-8707-11eb-960a-522a57ea7663.png)

I had to disable block limiter on our server for the time being so people can use projectors again.

**Comment by Blaylock1988** [comment]
Update: Setting General Grid Limits to 0, and 0, is now allowing projections correctly. Projections should not be affected by these settings.

**Comment by N1Ran** [comment]
How big is the grid that has the projector block?

**Comment by Blaylock1988** [comment]
The ship that was projecting was about 250 blocks and the projection was of the same ship so 250 block.
