### ISSUE TITLE
Command for add player ID, player name, faction,... to a specify limit name ?

### ISSUE THREAD

**Issue by Heliosanchez212** [N1Ran/BlockLimiter#88]
Hi there, 

Was looking  for a command to add a player to the limited items like

!blocklimit assign <player>  <limititem> <exception [boolean] >

Does this exist ?

i don't know if my request is clear enough, sorry for my english (i'm french ).
Thank you !

**Comment by N1Ran** [comment]
no such command exist.  Such as to be don via config file
