### ISSUE TITLE
[Bug] Running fixship causes playerlimits to increase incorrectly

### ISSUE THREAD

**Issue by kontu** [N1Ran/BlockLimiter#90]
https://user-images.githubusercontent.com/5705697/117035049-e4b2d680-acd1-11eb-9b6c-5e01cd4fbb44.mp4

I own 0 blocks in world
I place one shipgrinder, i have 1 limited.
I run !fixship on this one shipgrinder, it  claims i have 2.

Running !blocklimit update mylimit doesn't technically fix; it then tells me i have 0 shipwelders to my player
https://i.imgur.com/F8B18GH.png

Zero messaging in logs for any of this except the command runs

**Comment by kontu** [comment]
fyi logs coming soon

**Comment by N1Ran** [comment]
I can't reproduce this.  There might be something else involve

**Comment by kontu** [comment]
I'll dig deeper - nexus might be touching on a similar patch method, I'll report back what I find / any new data I have / if I find reproduction method w/ just blocklimiter alone

**Comment by kontu** [comment]
Torch install with only Blocklimiter, ALE ShipFixer, and SEWorldGen plugin installed, was still able to reproduce player limits increasing with every fixship
https://youtu.be/EnoLZsyPoSA

[Instance.zip](https://github.com/N1Ran/BlockLimiter/files/6522668/Instance.zip) <-- Copy of Saves, blocklimiter config, se-dedi.cfg, and shipfixer.cfg in the world i reproduced in

**Comment by N1Ran** [comment]
is SEWorldGen plugin a factor to this bug?

**Comment by kontu** [comment]
Always asking the difficult questions.....
Trialed with removing SEWorldgen from the above attached world; confirmed it is *not* related to SEWorldGen. I can still reproduce having only blocklimiter and ale shipfixer (which really; it's not just shipfixer that does this -- hangar save/load; even admin cut and paste can mess with it

**Comment by N1Ran** [comment]
seems I didn't set a method to catch grid closure and remove the counts of closed grids. bug confirmed
