### ISSUE TITLE
Not punish

### ISSUE THREAD

**Issue by marksman1907** [N1Ran/BlockLimiter#91]
Hello, I am adjusting the limit settings, but it definitely does not delete the blocks. The settings I made are in the picture. When I type "! blocklimit punish" I see a 0 punish.
![resim_2021-05-16_131828](https://user-images.githubusercontent.com/24860778/118393722-33a12a00-b649-11eb-963f-cebd78a6a019.png)

**Comment by N1Ran** [comment]
your punish interval is set to 300,000 seconds.  Except if your server is up for more than 83hrs, you will never see anyone punished.  I'd suggest bring it down close to 2x Annoy interval (600).
