### ISSUE TITLE
[Question]  Can different values be set up for individual users outside of "limit on" and "limit off"?

### ISSUE THREAD

**Issue by spradlin-dev** [N1Ran/BlockLimiter#92]
Mainly our server has been using block limit, but we're exploring the possibility of offering tiered block limit increases based on donations to the server budget.  Currently, our understanding is that we can change block limits on or off, per player, but we're not sure if we can set different tiers to assign users to.

**Comment by N1Ran** [comment]
You can make use of the exception for the limits.  There's a general exception and there is per limit exception.  You can set it in way where set of players have different limit to others
