### ISSUE TITLE
Win IO exception bug

### ISSUE THREAD

**Issue by zznty** [N1Ran/BlockLimiter#93]
**Problem:**
when plugin trying create file, it's do not release access to created file and can't read config

**Logs:**
it's causing error like [this](https://gist.github.com/f495626e81bb4938f1eb53098b2b40dc)

**Solution:**
call `.Dispose` for stream [here](https://github.com/N1Ran/BlockLimiter/blob/94f673971f80459e92f8c24109c41b9f9e915617/BlockLimiter/BlockLimiter.cs#L285) or use `.WriteAllText` to create empty text file.

**Comment by N1Ran** [comment]
done
