### ISSUE TITLE
Subgrid Detection not working

### ISSUE THREAD

**Issue by Asy93** [N1Ran/BlockLimiter#97]
With BL, if you ask the plugin to count subgrids, it doesnt seemt to work right.

We allow players a max of 50 guns per grid. If they have 49 guns, add 1 rotor, they can stick another 50 guns on it

**Comment by sisko91** [comment]
Helped test this out a bit more and can provide some more detail / reproduction steps

1. Add a basic limit on any block of 10
2. Create a grid with just one of that block. `!blocklimit mylimit` shows 1/10 in use
3. Create a rotor and add one of the limited block on the subgrid. `!blocklimit mylimit` shows 2/10 in use
4. Select the rotor and click detach to remove the subgrid. `!blocklimit mylimit` shows 2/10 in use, even though there's only one block now on the grid. Running `!blocklimit update mylimit` does not change this
5. Re-add the rotor and add one of the limited block on the subgrid. `!blocklimit mylimit` shows 3/10 (2 actually in use now)
6. Copy/paste the grid. `blocklimit mylimit` now only shows 1/10 in use, and does not count blocks already on the subgrid as belonging to the main grid. It will count new ones placed down, though

**Comment by sisko91** [comment]
Similarly you can just build subgrid separately and use the rotor "attach" button to connect it, and the limits wont be counted either

**Comment by N1Ran** [comment]
ok, I can work with this.  I should have a fix as soon as I can, but I get the gist of it.
